namespace ThorVGSharp.Interop;

internal enum Tvg_Blend_Method
{
    TVG_BLEND_METHOD_NORMAL = 0,
    TVG_BLEND_METHOD_MULTIPLY,
    TVG_BLEND_METHOD_SCREEN,
    TVG_BLEND_METHOD_OVERLAY,
    TVG_BLEND_METHOD_DARKEN,
    TVG_BLEND_METHOD_LIGHTEN,
    TVG_BLEND_METHOD_COLORDODGE,
    TVG_BLEND_METHOD_COLORBURN,
    TVG_BLEND_METHOD_HARDLIGHT,
    TVG_BLEND_METHOD_SOFTLIGHT,
    TVG_BLEND_METHOD_DIFFERENCE,
    TVG_BLEND_METHOD_EXCLUSION,
    TVG_BLEND_METHOD_HUE,
    TVG_BLEND_METHOD_SATURATION,
    TVG_BLEND_METHOD_COLOR,
    TVG_BLEND_METHOD_LUMINOSITY,
    TVG_BLEND_METHOD_ADD,
    TVG_BLEND_METHOD_COMPOSITION = 255,
}
