namespace ThorVGSharp.Interop;

internal enum Tvg_Mask_Method
{
    TVG_MASK_METHOD_NONE = 0,
    TVG_MASK_METHOD_ALPHA,
    TVG_MASK_METHOD_INVERSE_ALPHA,
    TVG_MASK_METHOD_LUMA,
    TVG_MASK_METHOD_INVERSE_LUMA,
    TVG_MASK_METHOD_ADD,
    TVG_MASK_METHOD_SUBTRACT,
    TVG_MASK_METHOD_INTERSECT,
    TVG_MASK_METHOD_DIFFERENCE,
    TVG_MASK_METHOD_LIGHTEN,
    TVG_MASK_METHOD_DARKEN,
}
